/*

 AUDIENCE_HAPPY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : audience_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 40
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define audience_happyWidth 20
#define audience_happyHeight 18
#define audience_happyBank 0

extern unsigned char audience_happy[];

/* End of AUDIENCE_HAPPY.H */
