/*

 AUDIENCE_NEUTRAL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : audience_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 40
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define audience_neutralWidth 20
#define audience_neutralHeight 18
#define audience_neutralBank 0

extern unsigned char audience_neutral[];

/* End of AUDIENCE_NEUTRAL.H */
