/*

 AUDIENCE_ANGRY.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : audience_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 40
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define audience_angryWidth 20
#define audience_angryHeight 18
#define audience_angryBank 0

extern unsigned char audience_angry[];

/* End of AUDIENCE_ANGRY.H */
