/*

 COMEDIAN_BACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : D:\Repo\hecklernightmare\hecklernightmare\res\standup tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define comedian_backgroundWidth 20
#define comedian_backgroundHeight 18
#define comedian_backgroundBank 0

extern unsigned char comedian_background[];

/* End of COMEDIAN_BACKGROUND.H */
